language: scala
scala:
  - 2.10.4
  - 2.11.1
script:
  - "cd $TRAVIS_BUILD_DIR/code"
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publish-local"
  - "cd $TRAVIS_BUILD_DIR/samples/play-easymail-usage"
  - "sbt ++$TRAVIS_SCALA_VERSION test"
notifications:
  email: false
